name: BlockDurabilityTweaks
version: 1.0.0
main: com.sorro.blockdurabilitytweaks.BlockDurabilityTweaks
api-version: "1.20"

softdepend: [ProtocolLib, WorldGuard]

commands:
  blockdurability:
    description: BlockDurabilityTweaks commands
    usage: /blockdurability <info|reload>

permissions:
  blockdurabilitytweaks.admin:
    default: op
  blockdurabilitytweaks.worldguard.bypass:
    default: op
