name: BlockDurabilityTweaks
version: 1.7.3
main: com.sorro.blockdurabilitytweaks.BlockDurabilityTweaks
api-version: "1.20"
softdepend: [ProtocolLib, WorldGuard]

commands:
  blockdurability:
    aliases: [bd]
    description: BlockDurabilityTweaks commands
    usage: /blockdurability <info|reload|gui|world|events>

permissions:
  blockdurabilitytweaks.admin:
    default: op
  blockdurabilitytweaks.worldguard.bypass:
    default: op
  blockdurabilitytweaks.gui.open:
    default: op

  blockdurabilitytweaks.events:
    default: op
  blockdurabilitytweaks.gui.open:
    default: op

permissions:
  blockdurabilitytweaks.inspect:
    default: op
