name: BlockDurabilityTweaks
version: 1.2.1
main: com.sorro.blockdurabilitytweaks.BlockDurabilityTweaks
api-version: "1.20"
softdepend: [ProtocolLib, WorldGuard]

commands:
  blockdurability:
    description: BlockDurabilityTweaks commands
    usage: /blockdurability <info|reload|world>

permissions:
  blockdurabilitytweaks.admin:
    default: op
  blockdurabilitytweaks.worldguard.bypass:
    default: op
  blockdurabilitytweaks.gui.open:
    default: op
